# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: kabrabom
  username: emival
  password: 123
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kabrabom
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kabrabom
  pool: 5
  timeout: 5000
